### ISSUE TITLE
pip to install another package?

### ISSUE THREAD

**Issue by braco** [Accenture/serverless-ephemeral#17]
What's the expected way to install an additional python library? [pandas](https://pandas.pydata.org/) in this case.

A little confused by the documentation, is it suggesting that another container needs to be created from scratch?

Or this format?
```
  - url: https://xxxxx.s3.amazonaws.com/boto3.zip
        nocache: true
```

**Comment by alexleonescalera** [comment]
The **url** option only works if you have a zip with all the necessary Python files already prebuilt. That means that you would have to pip install panda manually and zip all the necessary Python files.

I would recommend creating your own Docker container that installs that library, extending your Dockerfile from the existing (serephem-venv)[https://hub.docker.com/r/alexleonescalera/serephem-venv/] image. That way, serephem will take care of building including the necessary files every time.

You can just copy/paste/modify the Docker example for the [image-processor](https://github.com/Accenture/serverless-ephemeral/tree/master/examples/image-processor/docker). It uses Python Pillow image library, so you can just make the necessary replacements in the `build.sh` file.

**Comment by braco** [comment]
Thanks Alex!
